services:
  redis:
    image: "redis:latest"
    networks:
      - app-network
    ports:
      - "6379:6379"
    restart: unless-stopped
  auto-rsa:
    container_name: auto-rsa
    build: ./splitflow-buy
    ports:
      - "8080:8080"
    env_file:
      - .env
    tty: true
    volumes:
      - ./creds:/app/creds
networks:
  app-network:
    driver: bridge