services:
  splitflow:
    container_name: splitflow
    build: .
    env_file:
      - .env
    tty: true
    networks:
      - app-network
  redis:
    image: "redis:latest"
    networks:
      - app-network
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
  mongodb:
    image: "mongo:latest"
    networks:
      - app-network
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
  auto-rsa:
    container_name: auto-rsa
    build: ./splitflow-buy
    ports:
      - "8080:8080"
    env_file:
      - .env
    tty: true
    volumes:
      - ./creds:/app/creds
networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  mongo-data:

